### ISSUE TITLE
Compatibility with PHP CodeSniffer PHAR

### ISSUE THREAD

**Issue by filips123** [PHPCSStandards/PHPCSExtra#75]
I installed PHP CodeSniffer as PHAR using [Phive](https://phar.io/) tool. I want to use some features that PHPCSExtra and PHPCSUtils provide, but because they rely and require PHP CodeSniffer installed with Composer, it will be duplicated and probably won't work.

Is there any way how to install this to be compatible with PHP CodeSniffer in PHAR, without requiring to download duplicated dependencies using Composer?

**Comment by jrfnl** [comment]
@filips123 Yes there is, but that's not an installation method for which support is provided as it is quite (user-)error prone.
If you use it, you are on your own.

I will explain it here once and will refer to this issue for anyone asking about it after this.

Basically, you need to:
* Install PHPCSExtra and PHPCSUtils (and whatever other standards you use) using whatever method you prefer, from unzipping the release archives to using a git clone.
* Register the paths to where you installed PHPCSExtra and PHPCSUtils (and whatever other standards you use) with the PHPCS phar manually using `--config-set installed_paths path/to/PHPCSUtils,path/to/PHPCSExtra`.

Mind: `--config-set` will **overwrite** any existing setting for `installed_paths`, so you may want to run `--config-show` first to get the paths already registered and make sure you add those to the list when running `--config-set`.

Once you've done that, it should work fine with the Phar as all (non-dev) external dependencies are set up to work with the PHPCS autoloading system.

That's also the reason why you don't need to run `composer install --no-dev` for PHPCSUtils or PHPCSExtra after unzipping/cloning.

It's the setup I use in my dev environment myself, though with a git clone of PHPCS instead of the Phar.

Does that help ?

**Comment by jrfnl** [comment]
Oh and just for the record: when installing via Composer, you won't get duplicate installs, you will get each dependency only once with Composer doing the version negotiation to get a version of each dependency which is compatible with all requirements.

And to be totally clear, that is _once per project_ in which you set this up as a requirement or a hard _once_ if you set it up to be globally available via `composer global`.

**Comment by filips123** [comment]
Thanks for quick answer. I will try this, but I would still like some more user-friendly and less error-prone method.

I don't know how rulesets are registered with PHPCSExtra and PHPCSUtils, but would it work if PHPCS is removed from required dependency and moved into `suggest` and `require-dev`? So users who use PHPCS with Composer will have to explicitly require PHPCS in their dev dependencies, while users who don't use Composer for PHPCS will have to install it in other way (PHAR or from source). But I don't know if custom rulesets will still register automatically them.

> Oh and just for the record: when installing via Composer, you won't get duplicate installs, you will get each dependency only once with Composer doing the version negotiation to get a version of each dependency which is compatible with all requirements.

Yes, I meant duplicated between PHAR file and Composer dependency.

**Comment by jrfnl** [comment]
> I would still like some more user-friendly and less error-prone method.

That's why Composer is the preferred and only supported installation method and no, there is no other possible way to make this more user-friendly and less error-prone.

> I don't know how rulesets are registered with PHPCSExtra and PHPCSUtils

They aren't and don't need to be, but all standards need to be registered with your preferred install of PHPCS for them to work.

> would it work if PHPCS is removed from required dependency and moved into suggest and require-dev? 

No, it wouldn't.
1. This wouldn't make a difference at all for your usecase.
2. PHPCS is not a suggestion, but a hard dependency for both PHPCSUtils and PHPCSExtra. Without PHPCS, those just won't work. And as both have different version requirements/compatibilities, letting users require this themselves would make the Composer install method just as unreliable and error prone as the non-Composer one.

> But I don't know if custom rulesets will still register automatically them.

That should still work, but again, not something I'm willing to support.

**Comment by jrfnl** [comment]
> Yes, I meant duplicated between PHAR file and Composer dependency.

As I said above:

> you don't need to run `composer install --no-dev` for PHPCSUtils or PHPCSExtra after unzipping/cloning.

So if you follow my instructions above to the letter you will not end up with duplicate PHPCS installs.
